package main

type handler struct {
	method, handler, cmd, res, resType string
}

var handlers = []handler{
	{
		method:  "addnode",
		handler: "HandleAddNode",
		cmd:     "btcjson.AddNodeCmd",
		res:     "AddNodeRes",
		resType: "None",
	},
	{
		method:  "createrawtransaction",
		handler: "HandleCreateRawTransaction",
		cmd:     "btcjson.CreateRawTransactionCmd",
		res:     "CreateRawTransactionRes",
		resType: "string",
	},
	{
		method:  "decoderawtransaction",
		handler: "HandleDecodeRawTransaction",
		cmd:     "btcjson.DecodeRawTransactionCmd",
		res:     "DecodeRawTransactionRes",
		resType: "btcjson.TxRawDecodeResult",
	},
	{
		method:  "decodescript",
		handler: "HandleDecodeScript",
		cmd:     "btcjson.DecodeScriptCmd",
		res:     "DecodeScriptRes",
		resType: "btcjson.DecodeScriptResult",
	},
	{
		method:  "estimatefee",
		handler: "HandleEstimateFee",
		cmd:     "btcjson.EstimateFeeCmd",
		res:     "EstimateFeeRes",
		resType: "float64",
	},
	{
		method:  "generate",
		handler: "HandleGenerate",
		cmd:     "nil",
		res:     "GenerateRes",
		resType: "[]string",
	},
	{
		method:  "getaddednodeinfo",
		handler: "HandleGetAddedNodeInfo",
		cmd:     "btcjson.GetAddedNodeInfoCmd",
		res:     "GetAddedNodeInfoRes",
		resType: "[]btcjson.GetAddedNodeInfoResultAddr",
	},
	{
		method:  "getbestblock",
		handler: "HandleGetBestBlock",
		cmd:     "nil",
		res:     "GetBestBlockRes",
		resType: "btcjson.GetBestBlockResult",
	},
	{
		method:  "getbestblockhash",
		handler: "HandleGetBestBlockHash",
		cmd:     "nil",
		res:     "GetBestBlockHashRes",
		resType: "string",
	},
	{
		method:  "getblock",
		handler: "HandleGetBlock",
		cmd:     "btcjson.GetBlockCmd",
		res:     "GetBlockRes",
		resType: "btcjson.GetBlockVerboseResult",
	},
	{
		method:  "getblockchaininfo",
		handler: "HandleGetBlockChainInfo",
		cmd:     "nil",
		res:     "GetBlockChainInfoRes",
		resType: "btcjson.GetBlockChainInfoResult",
	},
	{
		method:  "getblockcount",
		handler: "HandleGetBlockCount",
		cmd:     "nil",
		res:     "GetBlockCountRes",
		resType: "int64",
	},
	{
		method:  "getblockhash",
		handler: "HandleGetBlockHash",
		cmd:     "btcjson.GetBlockHashCmd",
		res:     "GetBlockHashRes",
		resType: "string",
	},
	{
		method:  "getblockheader",
		handler: "HandleGetBlockHeader",
		cmd:     "btcjson.GetBlockHeaderCmd",
		res:     "GetBlockHeaderRes",
		resType: "btcjson.GetBlockHeaderVerboseResult",
	},
	{
		method:  "getblocktemplate",
		handler: "HandleGetBlockTemplate",
		cmd:     "btcjson.GetBlockTemplateCmd",
		res:     "GetBlockTemplateRes",
		resType: "string",
	},
	{
		method:  "getcfilter",
		handler: "HandleGetCFilter",
		cmd:     "btcjson.GetCFilterCmd",
		res:     "GetCFilterRes",
		resType: "string",
	},
	{
		method:  "getcfilterheader",
		handler: "HandleGetCFilterHeader",
		cmd:     "btcjson.GetCFilterHeaderCmd",
		res:     "GetCFilterHeaderRes",
		resType: "string",
	},
	{
		method:  "getconnectioncount",
		handler: "HandleGetConnectionCount",
		cmd:     "nil",
		res:     "GetConnectionCountRes",
		resType: "int32",
	},
	{
		method:  "getcurrentnet",
		handler: "HandleGetCurrentNet",
		cmd:     "nil",
		res:     "GetCurrentNetRes",
		resType: "string",
	},
	{
		method:  "getdifficulty",
		handler: "HandleGetDifficulty",
		cmd:     "btcjson.GetDifficultyCmd",
		res:     "GetDifficultyRes",
		resType: "float64",
	},
	{
		method:  "getgenerate",
		handler: "HandleGetGenerate",
		cmd:     "btcjson.GetHeadersCmd",
		res:     "GetGenerateRes",
		resType: "bool",
	},
	{
		method:  "gethashespersec",
		handler: "HandleGetHashesPerSec",
		cmd:     "nil",
		res:     "GetHashesPerSecRes",
		resType: "float64",
	},
	{
		method:  "getheaders",
		handler: "HandleGetHeaders",
		cmd:     "btcjson.GetHeadersCmd",
		res:     "GetHeadersRes",
		resType: "[]string",
	},
	{
		method:  "getinfo",
		handler: "HandleGetInfo",
		cmd:     "nil",
		res:     "GetInfoRes",
		resType: "btcjson.InfoChainResult0",
	},
	{
		method:  "getmempoolinfo",
		handler: "HandleGetMempoolInfo",
		cmd:     "nil",
		res:     "GetMempoolInfoRes",
		resType: "btcjson.GetMempoolInfoResult",
	},
	{
		method:  "getmininginfo",
		handler: "HandleGetMiningInfo",
		cmd:     "nil",
		res:     "GetMiningInfoRes",
		resType: "btcjson.GetMiningInfoResult",
	},
	{
		method:  "getnettotals",
		handler: "HandleGetNetTotals",
		cmd:     "nil",
		res:     "GetNetTotalsRes",
		resType: "btcjson.GetNetTotalsResult",
	},
	{
		method:  "getnetworkhashps",
		handler: "HandleGetNetworkHashPS",
		cmd:     "btcjson.GetNetworkHashPSCmd",
		res:     "GetNetworkHashPSRes",
		resType: "[]btcjson.GetPeerInfoResult",
	},
	{
		method:  "getpeerinfo",
		handler: "HandleGetPeerInfo",
		cmd:     "nil",
		res:     "GetPeerInfoRes",
		resType: "[]btcjson.GetPeerInfoResult",
	},
	{
		method:  "getrawmempool",
		handler: "HandleGetRawMempool",
		cmd:     "btcjson.GetRawMempoolCmd",
		res:     "GetRawMempoolRes",
		resType: "[]string",
	},
	{
		method:  "getrawtransaction",
		handler: "HandleGetRawTransaction",
		cmd:     "btcjson.GetRawTransactionCmd",
		res:     "GetRawTransactionRes",
		resType: "string",
	},
	{
		method:  "gettxout",
		handler: "HandleGetTxOut",
		cmd:     "btcjson.GetTxOutCmd",
		res:     "GetTxOutRes",
		resType: "string",
	},
	{
		method:  "help",
		handler: "HandleHelp",
		cmd:     "btcjson.HelpCmd",
		res:     "HelpRes",
		resType: "string",
	},
	{
		method:  "node",
		handler: "HandleNode",
		cmd:     "btcjson.NodeCmd",
		res:     "NodeRes",
		resType: "None",
	},
	{
		method:  "ping",
		handler: "HandlePing",
		cmd:     "nil",
		res:     "PingRes",
		resType: "None",
	},
	{
		method:  "searchrawtransactions",
		handler: "HandleSearchRawTransactions",
		cmd:     "btcjson.SearchRawTransactionsCmd",
		res:     "SearchRawTransactionsRes",
		resType: "[]btcjson.SearchRawTransactionsResult",
	},
	{
		method:  "sendrawtransaction",
		handler: "HandleSendRawTransaction",
		cmd:     "btcjson.SendRawTransactionCmd",
		res:     "SendRawTransactionRes",
		resType: "None",
	},
	{
		method:  "setgenerate",
		handler: "HandleSetGenerate",
		cmd:     "btcjson.SetGenerateCmd",
		res:     "SetGenerateRes",
		resType: "None",
	},
	{
		method:  "stop",
		handler: "HandleStop",
		cmd:     "nil",
		res:     "StopRes",
		resType: "None",
	},
	{
		method:  "restart",
		handler: "HandleRestart",
		cmd:     "nil",
		res:     "RestartRes",
		resType: "None",
	},
	{
		method:  "resetchain",
		handler: "HandleResetChain",
		cmd:     "nil",
		res:     "ResetChainRes",
		resType: "None",
	},
	{
		method:  "submitblock",
		handler: "HandleSubmitBlock",
		cmd:     "btcjson.SubmitBlockCmd",
		res:     "SubmitBlockRes",
		resType: "string",
	},
	{
		method:  "uptime",
		handler: "HandleUptime",
		cmd:     "nil",
		res:     "UptimeRes",
		resType: "btcjson.GetMempoolInfoResult",
	},
	{
		method:  "validateaddress",
		handler: "HandleValidateAddress",
		cmd:     "btcjson.ValidateAddressCmd",
		res:     "ValidateAddressRes",
		resType: "btcjson.ValidateAddressChainResult",
	},
	{
		method:  "verifychain",
		handler: "HandleVerifyChain",
		cmd:     "btcjson.VerifyChainCmd",
		res:     "VerifyChainRes",
		resType: "bool",
	},
	{
		method:  "verifymessage",
		handler: "HandleVerifyMessage",
		cmd:     "btcjson.VerifyMessageCmd",
		res:     "VerifyMessageRes",
		resType: "bool",
	},
	{
		method:  "version",
		handler: "HandleVersion",
		cmd:     "btcjson.VersionCmd",
		res:     "VersionRes",
		resType: "map[string]btcjson.VersionResult",
	},
}

func main() {

}
