package conf

import "github.com/parallelcointeam/parallelcoin/cmd/gui/vue/mod"

func GetPanels() map[string]mod.EJSlayout {
	return map[string]mod.EJSlayout{
		"overview": {
			Columns:           9,
			EnablePersistence: true,
			Panels: []mod.EJSpanel{
				{
					SizeX:    2,
					SizeY:    2,
					MinSizeX: 2,
					MinSizeY: 1,
					MaxSizeX: 3,
					MaxSizeY: 1,
					Col:      0,
					Row:      0,
					ZIndex:   0,
					ID:       "panelstatus",
					Header:   "<div class='e-header-text'>Status</div><div class='header-border'></div>",
					CssClass: "panel",
					Enabled:  true,
					Content:  "<div is='panelstatus' id='panelstatus' class='panel-content'></div>",
				},
				{
					SizeX:    2,
					SizeY:    1,
					MinSizeX: 2,
					MinSizeY: 1,
					MaxSizeX: 3,
					MaxSizeY: 1,
					Col:      2,
					Row:      0,
					ZIndex:   0,
					ID:       "panelwalletstatus",
					Header:   "<div class='e-header-text'>Wallet</div><div class='header-border'></div>",
					CssClass: "panel",
					Enabled:  true,
					Content:  "<div is='panelwalletstatus' id='panelwalletstatus' class='panel-content'></div>",
				},
				{
					SizeX:    2,
					SizeY:    1,
					MinSizeX: 2,
					MinSizeY: 1,
					MaxSizeX: 3,
					MaxSizeY: 1,
					Col:      5,
					Row:      0,
					ZIndex:   0,
					ID:       "panelnetworkhashrate",
					Header:   "<div class='e-header-text'>Network Hashrate</div><div class='header-border'></div>",
					CssClass: "panel",
					Enabled:  true,
					Content:  "<div is='panelnetworkhashrate' id='panelnetworkhashrate' class='panel-content'></div>",
				},
				{
					SizeX:    5,
					SizeY:    1,
					MinSizeX: 3,
					MinSizeY: 1,
					MaxSizeX: 5,
					MaxSizeY: 2,
					Col:      4,
					Row:      0,
					ZIndex:   0,
					ID:       "panelsend",
					Header:   "<div class='e-header-text'>Send</div><div class='header-border'></div>",
					CssClass: "noPanelFrame",
					Enabled:  true,
					Content:  "<div is='panelsend' id='panelsend' class='panel-content'></div>",
				},
				//{
				//	SizeX:    3,
				//	SizeY:    3,
				//	MinSizeX: 3,
				//	MinSizeY: 2,
				//	MaxSizeX: 9,
				//	MaxSizeY: 5,
				//	Col:      8,
				//	Row:      3,
				//	ZIndex:   0,
				//	ID:       "paneltest",
				//	Header:   <div class='e-header-text'>"Test</div><div class='header-border'></div>",
				//	CssClass: "panel",
				//	Enabled:  true,
				//	Content:  "<div is='paneltest' id='paneltest' class='panel-content'></div>test",
				//},
				{
					SizeX:    6,
					SizeY:    3,
					MinSizeX: 5,
					MinSizeY: 2,
					MaxSizeX: 9,
					MaxSizeY: 5,
					Col:      0,
					Row:      2,
					ZIndex:   0,
					ID:       "panelpeers",
					Header:   "<div class='e-header-text'>Peers</div><div class='header-border'></div>",
					CssClass: "panel",
					Enabled:  true,
					Content:  "<div is='panelpeers' id='panelpeers' class='panel-content'></div>",
				},
			},
		},
		"settings": {
			Columns:           9,
			EnablePersistence: true,
			Panels: []mod.EJSpanel{
				{
					SizeX:    5,
					SizeY:    3,
					MinSizeX: 3,
					MinSizeY: 2,
					MaxSizeX: 9,
					MaxSizeY: 5,
					Col:      0,
					Row:      0,
					ZIndex:   0,
					ID:       "paneldaemonconf",
					Header:   "<div class='e-header-text'>Daemon configuration</div><div class='header-border'></div>",
					CssClass: "panel",
					Enabled:  true,
					Content:  "<div is='paneldaemonconf' id='paneldaemonconf' class='panel-content'></div>",
				},
				//{
				//		SizeX:    1,
				//		SizeY:    1,
				//		MinSizeX: 1,
				//		MinSizeY: 1,
				//		MaxSizeX: 1,
				//		MaxSizeY: 1,
				//		Col:      1,
				//		Row:      0,
				//		ZIndex:   0,
				//		ID:       "panellayoutconfig",
				//		Header:   <div class='e-header-text'>"Layout configuration</div><div class='header-border'></div>",
				//		CssClass: "noPanelFrame",
				//		Enabled:  false,
				//		Content:  "<div class='panel-content' is='panellayoutconfig' id='panellayoutconfig'></div>",
				//	},
				{
					SizeX:    4,
					SizeY:    2,
					MinSizeX: 4,
					MinSizeY: 2,
					MaxSizeX: 9,
					MaxSizeY: 5,
					Col:      5,
					Row:      4,
					ZIndex:   0,
					ID:       "panelmanager",
					Header:   "<div class='e-header-text'>Manager</div><div class='header-border'></div>",
					CssClass: "panel",
					Enabled:  true,
					Content:  "<div is='panelmanager' id='panelmanager' class='panel-content'></div>",
				},
			},
			//},
		},
		//"blockexplorer": {
		//	Columns:           9,
		//	EnablePersistence: true,
		//	Panels: []mod.EJSpanel{
		//		{
		//			SizeX:    4,
		//			SizeY:    2,
		//			MinSizeX: 3,
		//			MinSizeY: 2,
		//			MaxSizeX: 9,
		//			MaxSizeY: 5,
		//			Col:      0,
		//			Row:      4,
		//			ZIndex:   0,
		//			ID:       "panelblockexplorer",
		//			Header:   "<div class='e-header-text'>Block Explorer</div><div class='header-border'></div>",
		//			CssClass: " ",
		//			Enabled:  false,
		//			Content:  "<div class='panel-content' is='panelblockexplorer' id='panelblockexplorer'></div>",
		//		},
		//	},
		//},
		"transactions": {
			Columns:           9,
			EnablePersistence: true,
			Panels: []mod.EJSpanel{
				{
					SizeX:    9,
					SizeY:    5,
					MinSizeX: 9,
					MinSizeY: 5,
					MaxSizeX: 9,
					MaxSizeY: 5,
					Col:      0,
					Row:      0,
					ZIndex:   0,
					ID:       "paneltransactions",
					Header:   "<div class='e-header-text'>Transactions</div><div class='header-border'></div>",
					CssClass: "panel",
					Enabled:  true,
					Content:  "<div class='panel-content' is='paneltransactions' id='paneltransactions'></div>",
				},
			},
		},
		"addressbook": {
			Columns:           9,
			EnablePersistence: true,
			Panels: []mod.EJSpanel{
				{
					SizeX:    9,
					SizeY:    5,
					MinSizeX: 9,
					MinSizeY: 5,
					MaxSizeX: 9,
					MaxSizeY: 5,
					Col:      0,
					Row:      0,
					ZIndex:   0,
					ID:       "paneladdressbook",
					Header:   "<div class='e-header-text'>Address Book</div><div class='header-border'></div>",
					CssClass: "panel",
					Enabled:  true,
					Content:  "<div class='panel-content' is='paneladdressbook' id='paneladdressbook'></div>",
				},
			},
		},
		"charts": {
			Columns:           9,
			EnablePersistence: true,
			Panels: []mod.EJSpanel{
				{
					SizeX:    4,
					SizeY:    2,
					MinSizeX: 3,
					MinSizeY: 2,
					MaxSizeX: 9,
					MaxSizeY: 5,
					Col:      0,
					Row:      0,
					ZIndex:   0,
					ID:       "panelcharta",
					Header:   "<div class='e-header-text'>Chart A</div><div class='header-border'></div>",
					CssClass: "panel",
					Enabled:  true,
					Content:  "<div is='panelcharta' id='panelcharta' class='panel-content'></div>",
				},
				{
					SizeX:    4,
					SizeY:    2,
					MinSizeX: 3,
					MinSizeY: 2,
					MaxSizeX: 9,
					MaxSizeY: 5,
					Col:      5,
					Row:      0,
					ZIndex:   0,
					ID:       "panelchartb",
					Header:   "<div class='e-header-text'>Chart B</div><div class='header-border'></div>",
					CssClass: "panel",
					Enabled:  true,
					Content:  "<div is='panelchartb' id='panelchartb' class='panel-content'></div>",
				},
			},
		},
	}
}
